apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.common.namespace }}
spec:
  selector:
    app: {{ .Values.common.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.ports.servicePort }}
    targetPort: {{ .Values.ports.containerPort }}
  type: {{ .Values.type }}