apiVersion: v1
kind: Service
metadata:
  name: image-uploader-service
  namespace: dev
spec:
  selector:
    app: image-uploader
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP