apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-uploader-pvc
  namespace: dev
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard